Feature/review images presigned
J-EUM/knewnew-project pull request #17
Opened 2022-09-02 09:52 UTC by J-EUM

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- presigned url

2022-09-06 03:43 UTC, Johnywhisky requested changes

2022-09-06 03:43 UTC, Johnywhisky commented on api/review/views.py
> +            config=Config(signature_version="s3v4"),
여기 config 제거해보시겠어요?

2022-09-06 03:43 UTC, Johnywhisky commented on api/review/views.py
> +        load_dotenv()
load_dotenv 는 manage.py에서 최초 1회 실행되는걸로 충분해요

2022-09-06 03:43 UTC, Johnywhisky commented on api/review/views.py
> +        load_dotenv()
`load_dotenv()`는 manage.py에서 최초 1회만 실행되면 돼요!

2022-09-06 03:43 UTC, Johnywhisky commented on config/settings.py
> +    # "django.middleware.csrf.CsrfViewMiddleware",
csrf 에러 때문에 주석처리 하신거에요??

2022-09-06 03:47 UTC, Johnywhisky requested changes

2022-09-06 03:47 UTC, Johnywhisky commented on api/review/views.py
> +        )
지금 잘 되고 있는거로 알고있긴 한데,
generate_presigned_post 안에 인자로
``` python
Fields={"acl": "public-read"},
Conditions=[{"acl": "public-read"}],
```
두개 옵션도 추가해보시겠어요??

2022-09-06 03:52 UTC, J-EUM commented on config/settings.py
> +    # "django.middleware.csrf.CsrfViewMiddleware",
네 맞습니다

2022-09-06 03:53 UTC, J-EUM commented on api/review/views.py
> +        )
넵

2022-09-06 03:53 UTC, J-EUM commented on api/review/views.py
> +        load_dotenv()
넵

2022-09-06 04:07 UTC, Johnywhisky commented on config/settings.py
> +    # "django.middleware.csrf.CsrfViewMiddleware",
그러면 cors 미들웨어를 csrf 미들웨어 위로 올리고, 주석 제거한 후에 api 호출 해보실래요??

2022-09-07 02:53 UTC, J-EUM commented on config/settings.py
> +    # "django.middleware.csrf.CsrfViewMiddleware",
잘됩니다~

2022-09-07 08:16 UTC, merged